//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectrosLtdApplication.TownServ {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TownServ.ITownService")]
    public interface ITownService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITownService/getAllTowns", ReplyAction="http://tempuri.org/ITownService/getAllTownsResponse")]
        Common.Town[] getAllTowns();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITownServiceChannel : ElectrosLtdApplication.TownServ.ITownService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TownServiceClient : System.ServiceModel.ClientBase<ElectrosLtdApplication.TownServ.ITownService>, ElectrosLtdApplication.TownServ.ITownService {
        
        public TownServiceClient() {
        }
        
        public TownServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TownServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TownServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TownServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Common.Town[] getAllTowns() {
            return base.Channel.getAllTowns();
        }
    }
}
