//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectrosLtdApplication.FaultServ {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FaultServ.IFaultService")]
    public interface IFaultService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFaultService/OrderItemHasFault", ReplyAction="http://tempuri.org/IFaultService/OrderItemHasFaultResponse")]
        Common.Fault OrderItemHasFault(int orderitemid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFaultService/AddFault", ReplyAction="http://tempuri.org/IFaultService/AddFaultResponse")]
        void AddFault(Common.Fault fault);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFaultService/GetAllFaults", ReplyAction="http://tempuri.org/IFaultService/GetAllFaultsResponse")]
        Common.Fault[] GetAllFaults();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFaultService/GetLastFault", ReplyAction="http://tempuri.org/IFaultService/GetLastFaultResponse")]
        Common.Fault GetLastFault();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFaultService/GetFaultById", ReplyAction="http://tempuri.org/IFaultService/GetFaultByIdResponse")]
        Common.Fault GetFaultById(int faultId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFaultServiceChannel : ElectrosLtdApplication.FaultServ.IFaultService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FaultServiceClient : System.ServiceModel.ClientBase<ElectrosLtdApplication.FaultServ.IFaultService>, ElectrosLtdApplication.FaultServ.IFaultService {
        
        public FaultServiceClient() {
        }
        
        public FaultServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FaultServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FaultServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FaultServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Common.Fault OrderItemHasFault(int orderitemid) {
            return base.Channel.OrderItemHasFault(orderitemid);
        }
        
        public void AddFault(Common.Fault fault) {
            base.Channel.AddFault(fault);
        }
        
        public Common.Fault[] GetAllFaults() {
            return base.Channel.GetAllFaults();
        }
        
        public Common.Fault GetLastFault() {
            return base.Channel.GetLastFault();
        }
        
        public Common.Fault GetFaultById(int faultId) {
            return base.Channel.GetFaultById(faultId);
        }
    }
}
