//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectrosLtdApplication.GenNumServ {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GenNumServ.IGenerateNumbers")]
    public interface IGenerateNumbers {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGenerateNumbers/GenerateTicketNo", ReplyAction="http://tempuri.org/IGenerateNumbers/GenerateTicketNoResponse")]
        int GenerateTicketNo();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGenerateNumbersChannel : ElectrosLtdApplication.GenNumServ.IGenerateNumbers, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GenerateNumbersClient : System.ServiceModel.ClientBase<ElectrosLtdApplication.GenNumServ.IGenerateNumbers>, ElectrosLtdApplication.GenNumServ.IGenerateNumbers {
        
        public GenerateNumbersClient() {
        }
        
        public GenerateNumbersClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GenerateNumbersClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GenerateNumbersClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GenerateNumbersClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int GenerateTicketNo() {
            return base.Channel.GenerateTicketNo();
        }
    }
}
