//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectrosLtdApplication.ReportServ {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ReportServ.IReportsService")]
    public interface IReportsService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportsService/HighlyRatedItem", ReplyAction="http://tempuri.org/IReportsService/HighlyRatedItemResponse")]
        Common.Rate[] HighlyRatedItem();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportsService/MostPurchasedItem", ReplyAction="http://tempuri.org/IReportsService/MostPurchasedItemResponse")]
        Common.OrderItem[] MostPurchasedItem();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportsService/HighestNumberFaults", ReplyAction="http://tempuri.org/IReportsService/HighestNumberFaultsResponse")]
        Common.ProductDTO[] HighestNumberFaults();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportsService/LowestNumberFaults", ReplyAction="http://tempuri.org/IReportsService/LowestNumberFaultsResponse")]
        Common.ProductDTO[] LowestNumberFaults();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IReportsServiceChannel : ElectrosLtdApplication.ReportServ.IReportsService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReportsServiceClient : System.ServiceModel.ClientBase<ElectrosLtdApplication.ReportServ.IReportsService>, ElectrosLtdApplication.ReportServ.IReportsService {
        
        public ReportsServiceClient() {
        }
        
        public ReportsServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReportsServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReportsServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReportsServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Common.Rate[] HighlyRatedItem() {
            return base.Channel.HighlyRatedItem();
        }
        
        public Common.OrderItem[] MostPurchasedItem() {
            return base.Channel.MostPurchasedItem();
        }
        
        public Common.ProductDTO[] HighestNumberFaults() {
            return base.Channel.HighestNumberFaults();
        }
        
        public Common.ProductDTO[] LowestNumberFaults() {
            return base.Channel.LowestNumberFaults();
        }
    }
}
