//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18449.
// 
#pragma warning disable 1591

namespace ElectrosLtdApplication.BarCodeServ {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BarCodeSoap", Namespace="http://www.webservicex.net/")]
    public partial class BarCode : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GenerateBarCodeOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public BarCode() {
            this.Url = global::ElectrosLtdApplication.Properties.Settings.Default.ElectrosLtdApplication_BarCodeServ_BarCode;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GenerateBarCodeCompletedEventHandler GenerateBarCodeCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.webservicex.net/GenerateBarCode", RequestNamespace="http://www.webservicex.net/", ResponseNamespace="http://www.webservicex.net/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] GenerateBarCode(BarCodeData BarCodeParam, string BarCodeText) {
            object[] results = this.Invoke("GenerateBarCode", new object[] {
                        BarCodeParam,
                        BarCodeText});
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        public void GenerateBarCodeAsync(BarCodeData BarCodeParam, string BarCodeText) {
            this.GenerateBarCodeAsync(BarCodeParam, BarCodeText, null);
        }
        
        /// <remarks/>
        public void GenerateBarCodeAsync(BarCodeData BarCodeParam, string BarCodeText, object userState) {
            if ((this.GenerateBarCodeOperationCompleted == null)) {
                this.GenerateBarCodeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGenerateBarCodeOperationCompleted);
            }
            this.InvokeAsync("GenerateBarCode", new object[] {
                        BarCodeParam,
                        BarCodeText}, this.GenerateBarCodeOperationCompleted, userState);
        }
        
        private void OnGenerateBarCodeOperationCompleted(object arg) {
            if ((this.GenerateBarCodeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GenerateBarCodeCompleted(this, new GenerateBarCodeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.webservicex.net/")]
    public partial class BarCodeData {
        
        private int heightField;
        
        private int widthField;
        
        private int angleField;
        
        private int ratioField;
        
        private int moduleField;
        
        private int leftField;
        
        private int topField;
        
        private bool checkSumField;
        
        private string fontNameField;
        
        private string barColorField;
        
        private string bGColorField;
        
        private float fontSizeField;
        
        private BarcodeOption barcodeOptionField;
        
        private BarcodeType barcodeTypeField;
        
        private CheckSumMethod checkSumMethodField;
        
        private ShowTextPosition showTextPositionField;
        
        private ImageFormats barCodeImageFormatField;
        
        /// <remarks/>
        public int Height {
            get {
                return this.heightField;
            }
            set {
                this.heightField = value;
            }
        }
        
        /// <remarks/>
        public int Width {
            get {
                return this.widthField;
            }
            set {
                this.widthField = value;
            }
        }
        
        /// <remarks/>
        public int Angle {
            get {
                return this.angleField;
            }
            set {
                this.angleField = value;
            }
        }
        
        /// <remarks/>
        public int Ratio {
            get {
                return this.ratioField;
            }
            set {
                this.ratioField = value;
            }
        }
        
        /// <remarks/>
        public int Module {
            get {
                return this.moduleField;
            }
            set {
                this.moduleField = value;
            }
        }
        
        /// <remarks/>
        public int Left {
            get {
                return this.leftField;
            }
            set {
                this.leftField = value;
            }
        }
        
        /// <remarks/>
        public int Top {
            get {
                return this.topField;
            }
            set {
                this.topField = value;
            }
        }
        
        /// <remarks/>
        public bool CheckSum {
            get {
                return this.checkSumField;
            }
            set {
                this.checkSumField = value;
            }
        }
        
        /// <remarks/>
        public string FontName {
            get {
                return this.fontNameField;
            }
            set {
                this.fontNameField = value;
            }
        }
        
        /// <remarks/>
        public string BarColor {
            get {
                return this.barColorField;
            }
            set {
                this.barColorField = value;
            }
        }
        
        /// <remarks/>
        public string BGColor {
            get {
                return this.bGColorField;
            }
            set {
                this.bGColorField = value;
            }
        }
        
        /// <remarks/>
        public float FontSize {
            get {
                return this.fontSizeField;
            }
            set {
                this.fontSizeField = value;
            }
        }
        
        /// <remarks/>
        public BarcodeOption barcodeOption {
            get {
                return this.barcodeOptionField;
            }
            set {
                this.barcodeOptionField = value;
            }
        }
        
        /// <remarks/>
        public BarcodeType barcodeType {
            get {
                return this.barcodeTypeField;
            }
            set {
                this.barcodeTypeField = value;
            }
        }
        
        /// <remarks/>
        public CheckSumMethod checkSumMethod {
            get {
                return this.checkSumMethodField;
            }
            set {
                this.checkSumMethodField = value;
            }
        }
        
        /// <remarks/>
        public ShowTextPosition showTextPosition {
            get {
                return this.showTextPositionField;
            }
            set {
                this.showTextPositionField = value;
            }
        }
        
        /// <remarks/>
        public ImageFormats BarCodeImageFormat {
            get {
                return this.barCodeImageFormatField;
            }
            set {
                this.barCodeImageFormatField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.webservicex.net/")]
    public enum BarcodeOption {
        
        /// <remarks/>
        None,
        
        /// <remarks/>
        Code,
        
        /// <remarks/>
        Typ,
        
        /// <remarks/>
        Both,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.webservicex.net/")]
    public enum BarcodeType {
        
        /// <remarks/>
        Code_2_5_interleaved,
        
        /// <remarks/>
        Code_2_5_industrial,
        
        /// <remarks/>
        Code_2_5_matrix,
        
        /// <remarks/>
        Code39,
        
        /// <remarks/>
        Code39Extended,
        
        /// <remarks/>
        Code128A,
        
        /// <remarks/>
        Code128B,
        
        /// <remarks/>
        Code128C,
        
        /// <remarks/>
        Code93,
        
        /// <remarks/>
        Code93Extended,
        
        /// <remarks/>
        CodeMSI,
        
        /// <remarks/>
        CodePostNet,
        
        /// <remarks/>
        CodeCodabar,
        
        /// <remarks/>
        CodeEAN8,
        
        /// <remarks/>
        CodeEAN13,
        
        /// <remarks/>
        CodeUPC_A,
        
        /// <remarks/>
        CodeUPC_E0,
        
        /// <remarks/>
        CodeUPC_E1,
        
        /// <remarks/>
        CodeUPC_Supp2,
        
        /// <remarks/>
        CodeUPC_Supp5,
        
        /// <remarks/>
        CodeEAN128A,
        
        /// <remarks/>
        CodeEAN128B,
        
        /// <remarks/>
        CodeEAN128C,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.webservicex.net/")]
    public enum CheckSumMethod {
        
        /// <remarks/>
        None,
        
        /// <remarks/>
        Modulo10,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.webservicex.net/")]
    public enum ShowTextPosition {
        
        /// <remarks/>
        TopLeft,
        
        /// <remarks/>
        TopRight,
        
        /// <remarks/>
        TopCenter,
        
        /// <remarks/>
        BottomLeft,
        
        /// <remarks/>
        BottomRight,
        
        /// <remarks/>
        BottomCenter,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.webservicex.net/")]
    public enum ImageFormats {
        
        /// <remarks/>
        BMP,
        
        /// <remarks/>
        EMF,
        
        /// <remarks/>
        EXIF,
        
        /// <remarks/>
        GIF,
        
        /// <remarks/>
        ICON,
        
        /// <remarks/>
        JPEG,
        
        /// <remarks/>
        MemoryBMP,
        
        /// <remarks/>
        PNG,
        
        /// <remarks/>
        TIFF,
        
        /// <remarks/>
        WMF,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GenerateBarCodeCompletedEventHandler(object sender, GenerateBarCodeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GenerateBarCodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GenerateBarCodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public byte[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591